### ISSUE TITLE
RHEL 8.6 - 8.7 container /w slurm

### ISSUE THREAD

**Issue by xlynxpro** [warewulf/warewulf-node-images#10]
I've been using RHEL 8.6 and 8.7. I'd like to know if there is a script out there that I could use to build a RHEL 8.6 or 8.7 container that contains slurm. I know there are some available containers out there like Rocky and CentOS but for the project that I'm working on, I need to use RHEL.

Side note- I tried using an UBI image from Redhat but when I imported it in wwctl, it wouldn't boot up.  

I also tried building an image from the host ( see below ) but no luck...

yum install --installroot /tmp/newroot basesystem bash \
    chkconfig coreutils e2fsprogs ethtool filesystem findutils \
    gawk grep initscripts iproute iputils net-tools nfs-utils pam \
    psmisc rsync sed setup shadow-utils rsyslog tzdata util-linux \
    words zlib tar less gzip which util-linux openssh-clients \
    openssh-server dhclient pciutils vim-minimal shadow-utils \
    strace cronie crontabs cpio wget redhat-release ipmitool yum \
    NetworkManager

Any help from you guys would be greatly appreciated.

**Comment by anderbubble** [comment]
I don't have any direct experience building a RHEL image for use with Warewulf yet; but if I were doing it I'd probably start with the Rocky Linux node image at https://github.com/hpcng/warewulf-node-images/tree/main/rockylinux-8 and change its `FROM` to point at an upstream Red Hat image. If that still didn't work, I'd be interested to know what error you get or behavior you see.

**Comment by anderbubble** [comment]
@xlynxpro I thought you'd be interested to know that we just published Rocky Linux 8.6 and 8.7 images. You can find them here:

* https://github.com/hpcng/warewulf-node-images/pkgs/container/warewulf-rockylinux/86776197?tag=8.6
* https://github.com/hpcng/warewulf-node-images/pkgs/container/warewulf-rockylinux/86776468?tag=8.7

I don't think we're likely to publish RHEL images due to access to the RHEL UBI, so I'm going to go ahead and close this out. But I'd be interested to hear about your experiences building an image using the RHEL UBI.
